spring:
  servlet:
    multipart:
      maxFileSize: 100MB

  datasource:
    username: sa
    password: 1q
    url: jdbc:h2:tcp://localhost/~/video
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true